export class AppTheme {
  static readonly BLUE: string = '#44A9F5';
  static readonly BLUE_DARK: string = '#147ED6';
  static readonly BLUE_LIGHT: string = '#E8F6FF';
  static readonly BORDER: string = '#C6E7FF';
  static readonly TEXT_MAIN: string = '#202D3D';
  static readonly TEXT_MUTED: string = '#697C91';
  static readonly BG: string = '#F7FBFF';
  static readonly WHITE: string = '#FFFFFF';
  static readonly DANGER: string = '#EC5252';
  static readonly GREEN: string = '#34A462';
  static readonly ORANGE: string = '#EB8334';
  static readonly PURPLE: string = '#8464D6';
  static readonly CYAN: string = '#2AA9B9';
  static readonly GRAY: string = '#667C94';
}
